---
abstract: 'Retrieve random numbers and data from random.org.'
author:
  - '-2014 Gregory Todd Williams. All rights reserved. This'
  - 'Gregory Todd Williams <gwilliams@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: '0.42'
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-RandomOrg
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  LWP: 0
  Math::BigInt: 1.15
  Scalar::Util: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05_03
